include: analysis_lint_rules.yaml

analyzer:

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  exclude:
    - "lib/**/*.g.dart"
    - "lib/**/*.gr.dart"
    - "lib/**/*.al.dart"
    - "lib/**/*.chopper.dart"
    - "lib/**/*.freezed.dart"
