name: auto_localized_generator
description: Code generator for auto_localized, runtime-safe Flutter localization.
version: 1.0.0
homepage: https://github.com/marcinsiedlik/auto_localized

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_localized: ^1.0.0
  build: ^1.6.0
  source_gen: ^0.9.10+3
  analyzer: ">=0.41.0 <2.0.0"
  recase: ^4.0.0-nullsafety.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.13