name: auto_localized_generator
description: Code generator for auto_localized.
version: 0.1.0
homepage: https://github.com/marcinsiedlik/auto_localized

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.3.0
  source_gen: ^0.9.6
  analyzer: ^0.39.14
  recase: ^3.0.0
  auto_localized: ^0.1.0

dev_dependencies:
  build_runner: ^1.10.1