name: auto_localized_generator
description: Code generator for auto_localized, runtime-safe Flutter localization.
version: 1.3.2
homepage: https://github.com/marcinsiedlik/auto_localized

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  auto_localized: ^1.3.2
  build: ^2.3.1
  source_gen: ^1.2.6
  analyzer: ^5.2.0
  recase: ^4.1.0
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.2