name: auto_localized_generator
description: Code generator for auto_localized, runtime-safe Flutter localization.
version: 1.3.3
homepage: https://github.com/marcinsiedlik/auto_localized

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  auto_localized: ^1.3.3
  build: ^2.4.1
  source_gen: ^1.4.0
  analyzer: ^6.2.0
  recase: ^4.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.6