name: auto_localized_generator
description: Code generator for auto_localized, runtime-safe Flutter localization.
version: 0.4.2
homepage: https://github.com/marcinsiedlik/auto_localized

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_localized: ^0.4.2
  build: ^1.3.0
  source_gen: ^0.9.6
  analyzer: ">=0.39.14 <0.41.0"
  recase: ^3.0.0
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.1