name: auto_localized_generator
description: Code generator for auto_localized, runtime-safe Flutter localization.
version: 1.3.0
homepage: https://github.com/marcinsiedlik/auto_localized

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  auto_localized: ^1.3.0
  build: ^2.1.1
  source_gen: ^1.2.0
  analyzer: ^3.0.0
  recase: ^4.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.7