name: example
description: An example for auto_localized library
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_localized: ^1.3.2

dev_dependencies:
  build_runner: ^2.3.2
  auto_localized_generator: ^1.3.2

flutter:

  uses-material-design: true
