name: example
description: An example for auto_localized library
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_localized: ^1.3.0

dev_dependencies:
  build_runner: ^2.1.7
  auto_localized_generator: ^1.3.0

flutter:

  uses-material-design: true
