name: auto_localized
description: Easy to use runtime-safe Flutter app localization tool using code generation.
version: 0.6.0
homepage: https://github.com/marcinsiedlik/auto_localized

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
